// Photo gallery: moments captured by the network's cameras, grouped by year.
// Add a photo: put <name>.webp (1600px wide) and <name>-sm.webp (720px) in img/gallery/<year>/,
// then add an entry below. `cam` links the photo to the live camera; `at` is local Greek time.
window.NHE_GALLERY = {
  2025: [
    { img: 'psarades-dawn', cam: 'psarades', at: '2025-04-07T06:43', tag: 'snow',
      place: { el: 'Ψαράδες, Πρέσπες', en: 'Psarades, Prespes' },
      text: { el: 'Χιονισμένο χωριό στην αυγή, με τις κορυφές πάνω από τη λίμνη να ροδίζουν.', en: 'A snowy village at dawn, with the peaks above the lake glowing pink.' } },
    { img: 'agiosathanasios-snow', cam: 'agiosathanasios', at: '2025-01-12T15:56', tag: 'snow',
      place: { el: 'Άγιος Αθανάσιος, Πέλλα', en: 'Agios Athanasios, Pella' },
      text: { el: 'Τα έλατα λυγίζουν από το φρέσκο χιόνι που πέφτει ασταμάτητα.', en: 'The fir trees bend under fresh snow that keeps falling.' } },
    { img: 'xinonero-snow', cam: 'xinonero', at: '2025-01-12T18:38', tag: 'snow',
      place: { el: 'Ξινό Νερό, Φλώρινα', en: 'Xino Nero, Florina' },
      text: { el: 'Νύχτα με χιονόπτωση και τα φώτα του δρόμου να χάνονται στην ομίχλη.', en: 'Snowfall at night, the street lights fading into the mist.' } },
    { img: 'palaiochori-night', cam: 'palaiochori', at: '2025-01-12T23:30', tag: 'snow',
      place: { el: 'Παλαιοχώρι, Χαλκιδική', en: 'Palaiochori, Chalkidiki' },
      text: { el: 'Ήσυχη νύχτα και οι στέγες του χωριού ασπρίζουν κάτω από το χιόνι.', en: 'A quiet night as the village roofs turn white under the snow.' } },
    { img: 'psarades-night', cam: 'psarades', at: '2025-01-12T23:45', tag: 'snow',
      place: { el: 'Ψαράδες, Πρέσπες', en: 'Psarades, Prespes' },
      text: { el: 'Τα φώτα του χωριού λάμπουν στο χιόνι δίπλα στη σκοτεινή λίμνη.', en: 'The village lights shine on the snow beside the dark lake.' } },
    { img: 'naousa-snow', cam: 'naousa', at: '2025-01-13T12:14', tag: 'snow',
      place: { el: 'Νάουσα, Ημαθία', en: 'Naousa, Imathia' },
      text: { el: 'Μεσημέρι και η πόλη χάνεται κάτω από πυκνή χιονόπτωση.', en: 'Midday, and the town disappears under heavy snowfall.' } },
    { img: 'soufli-snow', cam: 'soufli', at: '2025-01-14T07:32', tag: 'snow',
      place: { el: 'Σουφλί, Έβρος', en: 'Soufli, Evros' },
      text: { el: 'Χιονισμένες στέγες και λευκά χωράφια ως τον ορίζοντα του Έβρου.', en: 'Snowy roofs and white fields stretching to the Evros horizon.' } },
    { img: 'derveni-snow', cam: 'derveni', at: '2025-01-14T08:02', tag: 'snow',
      place: { el: 'Δερβένι, Θεσσαλονίκη', en: 'Derveni, Thessaloniki' },
      text: { el: 'Το χιόνι σκεπάζει τον λόφο ενώ ροζ φως ανοίγει πάνω από τον κάμπο.', en: 'Snow covers the hillside as pink light opens over the plain.' } },
    { img: 'palaiochori-night2', cam: 'palaiochori', at: '2025-01-15T21:17', tag: 'snow',
      place: { el: 'Παλαιοχώρι, Χαλκιδική', en: 'Palaiochori, Chalkidiki' },
      text: { el: 'Βαθύ χιόνι στις στέγες και ομίχλη που κατεβαίνει στο χωριό.', en: 'Deep snow on the roofs and mist rolling down into the village.' } },
    { img: 'psarades-march', cam: 'psarades', at: '2025-03-18T09:33', tag: 'snow',
      place: { el: 'Ψαράδες, Πρέσπες', en: 'Psarades, Prespes' },
      text: { el: 'Χιονοθύελλα του Μαρτίου κρύβει τη λίμνη και τα βουνά.', en: 'A March snowstorm hides the lake and the mountains.' } },
    { img: 'palaiochori-dawn', cam: 'palaiochori', at: '2025-03-19T06:00', tag: 'snow',
      place: { el: 'Παλαιοχώρι, Χαλκιδική', en: 'Palaiochori, Chalkidiki' },
      text: { el: 'Το φεγγάρι πάνω από τις χιονισμένες στέγες και τα φώτα του δρόμου.', en: 'The moon above the snowy roofs and the glowing street.' } },
    { img: 'agiosathanasios-dawn', cam: 'agiosathanasios', at: '2025-04-07T06:46', tag: 'snow',
      place: { el: 'Άγιος Αθανάσιος, Πέλλα', en: 'Agios Athanasios, Pella' },
      text: { el: 'Ανοιξιάτικο χιόνι στην αυγή, με τη χιονισμένη κορυφή στο βάθος.', en: 'April snow at dawn, with the snowy summit in the distance.' } },
    { img: 'liti-snow', cam: 'liti', at: '2025-04-07T07:07', tag: 'snow',
      place: { el: 'Λητή, Θεσσαλονίκη', en: 'Liti, Thessaloniki' },
      text: { el: 'Χιόνι τον Απρίλιο σκεπάζει το γήπεδο και τις στέγες της Λητής.', en: 'April snow covers the pitch and the roofs of Liti.' } },
    { img: 'olympus-snow', at: '2025-04-07T07:33', tag: 'snow',
      place: { el: 'Όλυμπος, Πιερία', en: 'Mount Olympus, Pieria' },
      text: { el: 'Οι πρόποδες του Ολύμπου ντύθηκαν στα λευκά ένα πρωί του Απριλίου.', en: 'The foothills of Olympus dressed in white on an April morning.' } }
  ],
  2024: [
    { img: 'alexandroupoli-lightning', cam: 'alexfaros', at: '2024-09-29T20:15', tag: 'lightning',
      place: { el: 'Φάρος Αλεξανδρούπολης, Έβρος', en: 'Alexandroupoli lighthouse, Evros' },
      text: { el: 'Δύο κεραυνοί χτυπούν τη θάλασσα ακριβώς μπροστά από τον φάρο.', en: 'Two lightning bolts strike the sea right in front of the lighthouse.' } },
    { img: 'derveni-snow', cam: 'derveni', at: '2024-01-21T00:26', tag: 'snow',
      place: { el: 'Δερβένι, Θεσσαλονίκη', en: 'Derveni, Thessaloniki' },
      text: { el: 'Μεσάνυχτα και χιονισμένοι λόφοι, με τα φώτα της πόλης να λάμπουν στον κάμπο.', en: 'Midnight on snowy hills, with the city lights glowing across the plain.' } },
    { img: 'liti-snow', cam: 'liti', at: '2024-01-21T00:27', tag: 'snow',
      place: { el: 'Λητή, Θεσσαλονίκη', en: 'Liti, Thessaloniki' },
      text: { el: 'Την ίδια νύχτα, το χιόνι ασπρίζει στέγες και χωράφια στη Λητή.', en: 'The same night, snow whitens the roofs and fields of Liti.' } },
    { img: 'neraida-snow', cam: 'neraida', at: '2024-01-21T09:19', tag: 'snow',
      place: { el: 'Νεράιδα, Λίμνη Πολυφύτου', en: 'Neraida, Lake Polyfytos' },
      text: { el: 'Το πρωί, χιονισμένες όχθες γύρω από τη σκοτεινή λίμνη και τη γέφυρα.', en: 'In the morning, snowy shores around the dark lake and the bridge.' } },
    { img: 'florina', cam: 'florina', at: '2024-01-21T09:19', tag: 'snow',
      place: { el: 'Φλώρινα', en: 'Florina' },
      text: { el: 'Πυκνή χιονόπτωση στην πόλη, δίπλα στο ποτάμι και τα παλιά αρχοντικά.', en: 'Heavy snowfall in town, beside the river and the old mansions.' } },
    { img: 'alexandroupoli-sunset', cam: 'alexfaros', at: '2024-02-04T17:38', tag: 'sunset',
      place: { el: 'Φάρος Αλεξανδρούπολης, Έβρος', en: 'Alexandroupoli lighthouse, Evros' },
      text: { el: 'Ροζ σύννεφα στο ηλιοβασίλεμα πάνω από τον φάρο και τη θάλασσα.', en: 'Pink clouds at sunset over the lighthouse and the sea.' } },
    { img: 'makrigialos-rainbow', cam: 'makrigialos', at: '2024-03-07T16:33', tag: 'rainbow',
      place: { el: 'Μακρύγιαλος, Πιερία', en: 'Makrygialos, Pieria' },
      text: { el: 'Ένα ολόκληρο ουράνιο τόξο υψώνεται πάνω από τη θάλασσα.', en: 'A full rainbow rises over the sea.' } },
    { img: 'derveni-rainbow', cam: 'derveni', at: '2024-04-07T17:52', tag: 'rainbow',
      place: { el: 'Δερβένι, Θεσσαλονίκη', en: 'Derveni, Thessaloniki' },
      text: { el: 'Ουράνιο τόξο ανάμεσα σε γαλάζιο ουρανό και τη βροχή που φεύγει.', en: 'A rainbow between blue sky and the passing rain.' } },
    { img: 'platamonas-rainbow', cam: 'platamonas', at: '2024-04-21T17:33', tag: 'rainbow',
      place: { el: 'Κάστρο Πλαταμώνα, Πιερία', en: 'Platamon Castle, Pieria' },
      text: { el: 'Ουράνιο τόξο αγκαλιάζει το κάστρο του Πλαταμώνα.', en: 'A rainbow embraces Platamon Castle.' } },
    { img: 'makrigialos-storm', cam: 'makrigialos', at: '2024-06-28T17:03', tag: 'storm',
      place: { el: 'Μακρύγιαλος, Πιερία', en: 'Makrygialos, Pieria' },
      text: { el: 'Καλοκαιρινή μπόρα φέρνει κύματα και σκοτεινό ουρανό στην παραλία.', en: 'A summer storm brings waves and a dark sky to the beach.' } },
    { img: 'kalamaria-lightning', cam: 'noth', at: '2024-07-11T22:09', tag: 'lightning',
      place: { el: 'Ν.Ο. Θεσσαλονίκης, Καλαμαριά', en: 'Thessaloniki Nautical Club, Kalamaria' },
      text: { el: 'Κεραυνός πέφτει στον Θερμαϊκό, πίσω από τα κατάρτια των σκαφών.', en: 'Lightning strikes the Thermaic Gulf behind the boat masts.' } },
    { img: 'naousa-lightning', cam: 'naousa', at: '2024-08-18T20:35', tag: 'lightning',
      place: { el: 'Νάουσα, Ημαθία', en: 'Naousa, Imathia' },
      text: { el: 'Ένας κεραυνός φωτίζει τον πορτοκαλί ουρανό πάνω από την πόλη.', en: 'A lightning bolt lights up the orange sky over the town.' } },
    { img: 'olympus-storm', at: '2024-08-18T20:44', tag: 'storm',
      place: { el: 'Όλυμπος, Πιερία', en: 'Mount Olympus, Pieria' },
      text: { el: 'Η καταιγίδα βάφει πορτοκαλί τον ουρανό πάνω από τις πλαγιές του Ολύμπου.', en: 'The storm turns the sky orange above the slopes of Olympus.' } },
    { img: 'agiosathanasios-snow', cam: 'agiosathanasios', at: '2024-12-26T09:06', tag: 'snow',
      place: { el: 'Άγιος Αθανάσιος, Πέλλα', en: 'Agios Athanasios, Pella' },
      text: { el: 'Χιονίζει στα 1.200 μέτρα, την επόμενη μέρα των Χριστουγέννων.', en: 'Snow falling at 1,200 m, the day after Christmas.' } },
    { img: 'agiosathanasios-sun', cam: 'agiosathanasios', at: '2024-12-27T09:28', tag: 'snow',
      place: { el: 'Άγιος Αθανάσιος, Πέλλα', en: 'Agios Athanasios, Pella' },
      text: { el: 'Την επόμενη μέρα ο ήλιος βγαίνει και το χωριό αχνίζει μέσα στο χιόνι.', en: 'The next day the sun comes out and the village steams in the snow.' } },
    { img: 'olympus-clouds', at: '2024-12-28T16:24', tag: 'clouds',
      place: { el: 'Όλυμπος, Πιερία', en: 'Mount Olympus, Pieria' },
      text: { el: 'Φακοειδή σύννεφα σαν καπέλο πάνω από τις χιονισμένες κορυφές του Ολύμπου.', en: 'Lenticular clouds sit like a hat over the snowy peaks of Olympus.' } }
  ],
  2023: [
    { img: 'alexandroupoli', cam: 'alexfaros', at: '2023-06-18T16:29', tag: 'shelf',
      place: { el: 'Φάρος Αλεξανδρούπολης, Έβρος', en: 'Alexandroupoli lighthouse, Evros' },
      text: { el: 'Ένα τεράστιο shelf cloud έρχεται από τη θάλασσα πάνω από τον φάρο.', en: 'A huge shelf cloud rolls in from the sea over the lighthouse.' } },
    { img: 'neraida', cam: 'neraida', at: '2023-01-21T08:29', tag: 'sunrise',
      place: { el: 'Νεράιδα, Λίμνη Πολυφύτου', en: 'Neraida, Lake Polyfytos' },
      text: { el: 'Ο πρωινός ήλιος σπάει τα σύννεφα και λάμπει πάνω στη λίμνη και τη γέφυρα.', en: 'The morning sun breaks through the clouds and shines on the lake and the bridge.' } },
    { img: 'nymfaio', at: '2023-01-29T07:58', tag: 'snow',
      place: { el: 'Νυμφαίο, Φλώρινα', en: 'Nymfaio, Florina' },
      text: { el: 'Χιονισμένο ξημέρωμα στα 1.350 μέτρα, με το πρώτο φως να βάφει χρυσά τα σπίτια.', en: 'A snowy dawn at 1,350 m, with the first light turning the houses gold.' } },
    { img: 'neraida-rainbow', cam: 'neraida', at: '2023-03-04T17:01', tag: 'rainbow',
      place: { el: 'Νεράιδα, Λίμνη Πολυφύτου', en: 'Neraida, Lake Polyfytos' },
      text: { el: 'Διπλό ουράνιο τόξο πέφτει μέσα στη λίμνη, δίπλα στη γέφυρα.', en: 'A double rainbow drops into the lake beside the bridge.' } },
    { img: 'derveni-rainbow2', cam: 'derveni', at: '2023-03-27T19:07', tag: 'rainbow',
      place: { el: 'Δερβένι, Θεσσαλονίκη', en: 'Derveni, Thessaloniki' },
      text: { el: 'Ολόκληρο ουράνιο τόξο αγκαλιάζει τη λεκάνη του Λαγκαδά.', en: 'A full rainbow arches over the Lagadas basin.' } },
    { img: 'derveni-rainbow', cam: 'derveni', at: '2023-04-01T17:41', tag: 'rainbow',
      place: { el: 'Δερβένι, Θεσσαλονίκη', en: 'Derveni, Thessaloniki' },
      text: { el: 'Ξανά ουράνιο τόξο, λίγες μέρες μετά, πάνω από τον πράσινο κάμπο.', en: 'Another rainbow a few days later, over the green plain.' } },
    { img: 'dikaia', cam: 'dikaia', at: '2023-04-04T17:06', tag: 'shelf',
      place: { el: 'Δίκαια, Έβρος', en: 'Dikaia, Evros' },
      text: { el: 'Ένα shelf cloud απλώνεται πάνω από τα κεραμίδια του χωριού.', en: 'A shelf cloud spreads over the village rooftops.' } },
    { img: 'kalamaria', cam: 'noth', at: '2023-04-22T18:11', tag: 'shelf',
      place: { el: 'Ν.Ο. Θεσσαλονίκης, Καλαμαριά', en: 'Thessaloniki Nautical Club, Kalamaria' },
      text: { el: 'Shelf cloud στον Θερμαϊκό, λίγο πριν φτάσει στα σκάφη του ομίλου.', en: 'A shelf cloud covers the Thermaic Gulf, just before it reaches the club’s boats.' } },
    { img: 'makrigialos', cam: 'makrigialos', at: '2023-04-22T19:07', tag: 'shelf',
      place: { el: 'Μακρύγιαλος, Πιερία', en: 'Makrygialos, Pieria' },
      text: { el: 'Την ίδια μέρα, μια ώρα αργότερα, το ίδιο shelf cloud απλώνεται πάνω από τη θάλασσα.', en: 'The same day, an hour later, the same shelf cloud stretches across the sea.' } }
  ],
  2022: [
    { img: 'liti', cam: 'liti', at: '2022-09-17T19:08', tag: 'shelf',
      place: { el: 'Λητή, Θεσσαλονίκη', en: 'Liti, Thessaloniki' },
      text: { el: 'Ένα τεράστιο shelf cloud σκεπάζει τον κάμπο πάνω από τη Λητή Θεσσαλονίκης.', en: 'A huge shelf cloud rolls over the plain above Liti.' } },
    { img: 'soufli', cam: 'soufli', at: '2022-01-12T10:53', tag: 'snow',
      place: { el: 'Σουφλί, Έβρος', en: 'Soufli, Evros' },
      text: { el: 'Χιονισμένο πρωινό στο Σουφλί, δίπλα στις γραμμές του τρένου.', en: 'A snowy morning in Soufli, next to the railway line.' } },
    { img: 'dikaia', cam: 'dikaia', at: '2022-02-03T07:24', tag: 'snow',
      place: { el: 'Δίκαια, Έβρος', en: 'Dikaia, Evros' },
      text: { el: 'Τα Δίκαια ξυπνάνε κάτω από ένα λευκό πάπλωμα χιονιού.', en: 'Dikaia wakes up under a white blanket of snow.' } },
    { img: 'panteleimonas', cam: 'panteleimonas', at: '2022-03-09T06:35', tag: 'snow',
      place: { el: 'Νέος Παντελεήμονας, Πιερία', en: 'Neos Panteleimonas, Pieria' },
      text: { el: 'Χιονοθύελλα πριν το ξημέρωμα, με τα φώτα να λάμπουν μέσα στην ομίχλη.', en: 'A blizzard before dawn, with lights glowing through the fog.' } },
    { img: 'derveni', cam: 'derveni', at: '2022-08-24T20:15', tag: 'storm',
      place: { el: 'Δερβένι, Θεσσαλονίκη', en: 'Derveni, Thessaloniki' },
      text: { el: 'Σύννεφα καταιγίδας απλώνονται πάνω από τον κάμπο της Θεσσαλονίκης.', en: 'Storm clouds spread over the Thessaloniki plain.' } },
    { img: 'makrigialos', cam: 'makrigialos', at: '2022-09-06T07:05', tag: 'sunrise',
      place: { el: 'Μακρύγιαλος, Πιερία', en: 'Makrygialos, Pieria' },
      text: { el: 'Ο ήλιος ανατέλλει πάνω από τον Θερμαϊκό, κάτω από βαριά σύννεφα.', en: 'The sun rises over the Thermaic Gulf beneath heavy clouds.' } }
  ]
};
